services:
  - type: web
    name: gold-price-tracker
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn -b 0.0.0.0:5000 app:app
